web-workout-tracker/workout/.env
web-workout-tracker/workout/package.json
web-workout-tracker/workout/src/App.js
web-workout-tracker/workout/src/auth_config.json
web-workout-tracker/workout/src/components/Navbar.js
web-workout-tracker/workout/src/components/Profile.js
web-workout-tracker/workout/src/index.js
web-workout-tracker/workout/src/react-auth0-wrapper.js
web-workout-tracker/workout/yarn.lock

the vanilla basic Auth0 implementation with a google login in the configuration. Started on a profile options as well, but haven't fully implemented that.

Auth setup

---

web-workout-tracker/workout/src/components/Button.js
web-workout-tracker/workout/src/components/ButtonWithBackground.js
web-workout-tracker/workout/src/components/OnboardingHeader.js
web-workout-tracker/workout/src/views/App.js
web-workout-tracker/workout/src/views/BodyGoal.js

This is a new feature for the on boarding process for the new user, where he is required to choose his body goal.
No tests yet.

Web on boarding process - Set body goal

---

web-workout-tracker/workout/src/components/Button.js
web-workout-tracker/workout/src/components/ButtonWithBackground.js
web-workout-tracker/workout/src/components/OnboardingHeader.js
web-workout-tracker/workout/src/design/global_style.js
web-workout-tracker/workout/src/views/BodyGoal.js

Made on boarding closer to the design. Still needs some changes.

Web onboarding process

---

web-workout-tracker/workout/src/components/Button.js
web-workout-tracker/workout/src/components/ButtonWithBackground.js
web-workout-tracker/workout/src/components/OnboardingHeader.js
web-workout-tracker/workout/src/views/BodyGoal.js

Finished styling for Select button

Web onboarding process - Finished styling for Select button

---

web-workout-tracker/workout/src/views/App.js
web-workout-tracker/workout/src/views/Landing.js
web-workout-tracker/workout/src/views/Profile.js
web-workout-tracker/workout/src/views/user_settings/index.js

Simplified Profile options and added them into the settings tab. Also, took Profile out of the Landing page as it will now be housed under user-settings. No styling yet.

Added in Profile to Settings view

---

web-workout-tracker/workout/src/components/Button.js
web-workout-tracker/workout/src/components/ButtonWithBackground.js
web-workout-tracker/workout/src/views/BodyGoal.js

Fixed padding props on Button component, added checkmark on ButtonWithBackground (body goal) component, made it dynamic (visible only when button is active).

Web onboarding process - 

---

web-workout-tracker/workout/package.json
web-workout-tracker/workout/src/views/App.js
web-workout-tracker/workout/src/views/Landing.js
web-workout-tracker/workout/yarn.lock

moved log workout to the landing page. added in a calendar view. zero styling is done so far. 

Landing Page Functionality

---

web-workout-tracker/workout/public/index.html

Updated link for the font to match exact type of Roboto Condensed font

Updated link for the font to match exact type of Roboto Condensed font

---

web-workout-tracker/workout/src/views/Profile.js
web-workout-tracker/workout/src/views/user_settings/index.js

Fixed Profile Photo for mobile and centered 

User settings design-fix

---

web-workout-tracker/workout/package.json
web-workout-tracker/workout/yarn.lock

Just added dependencies for testing React components.

Added dependencies for testing

---

web-workout-tracker/workout/package.json
web-workout-tracker/workout/src/__tests__/BodyGoal.test.js
web-workout-tracker/workout/src/__tests__/ButtonWithBackground.test.js
web-workout-tracker/workout/src/__tests__/__snapshots__/BodyGoal.test.js.snap
web-workout-tracker/workout/src/components/Button.js
web-workout-tracker/workout/src/components/ButtonWithBackground.js
web-workout-tracker/workout/src/components/OnboardingHeader.js
web-workout-tracker/workout/src/views/BodyGoal.js
web-workout-tracker/workout/yarn.lock

Tests for on boarding

---

web-workout-tracker/workout/src/components/Navbar.js
web-workout-tracker/workout/src/views/App.js
web-workout-tracker/workout/src/views/Landing.js
web-workout-tracker/workout/src/views/ValidateUser.js

Updates navbar to render certain buttons if in onboarding screen or dashboard. Updated validate user component to post new user to backend, set user_id to local storage, and send user to onboarding if new.

Web validate user

---

web-workout-tracker/workout/src/components/Navbar.js
web-workout-tracker/workout/src/views/ValidateUser.js
web-workout-tracker/workout/src/views/Workouts.js

export auth0 function for marketing page

---

web-workout-tracker/workout/src/actions/index.js
web-workout-tracker/workout/src/components/Navbar.js
web-workout-tracker/workout/src/reducers/index.js
web-workout-tracker/workout/src/views/Landing.js
web-workout-tracker/workout/src/views/ValidateUser.js

added action to send auth0 data to redux store.

when auth0 finishes, sends data to redux store

---

marketing-site/index.html

Login button from the marketing site directs users to react app. Looks to be functioning correctly.
- [] I have made corresponding changes to the documentation

Login button on marketing site directs user to react app

---

web-workout-tracker/workout/src/views/App.js
web-workout-tracker/workout/src/views/DropDownInfo.js
web-workout-tracker/workout/src/views/DropdownLogs.js
web-workout-tracker/workout/src/views/landing/Workouts.js
web-workout-tracker/workout/src/views/workout_form/WorkoutInputForm.js

Fixed rendering component correctly if signed in or not, and styled workout form data display.

rendering data is now styled

---

web-workout-tracker/workout/src/views/Profile.js
web-workout-tracker/workout/src/views/user_settings/index.js

connecting Body Goal to user settings

Pull bodygoal into settings

---

web-workout-tracker/workout/src/components/Navbar.js

temp login fix

---

web-workout-tracker/workout/src/components/Navbar.js

typo fixes

---

web-workout-tracker/workout/src/__tests__/__snapshots__/BodyGoal.test.js.snap
web-workout-tracker/workout/src/components/Button.js
web-workout-tracker/workout/src/components/ButtonWithBackground.js
web-workout-tracker/workout/src/views/BodyGoal.js

Fixed issue with Select button. Also added a new feature: now user can skip on boarding process using a special button and go straight to the landing page 

Select button and skip on boarding

---

web-workout-tracker/workout/src/views/user_settings/index.js

Made User Settings component pull data for body goal from right Redux store state object.

Body goal in settings

---

marketing-site/css/index.css
marketing-site/index.html

Removed both google and apple download buttons as well as fixed some issues with styling.

Cleaned up site, should look more presentable.

---

web-workout-tracker/workout/src/views/BodyGoal.js
web-workout-tracker/workout/src/views/user_settings/index.js

Added ability for user to change his body goal in the settings

Body goal in the settings

---

web-workout-tracker/workout/src/actions/index.js
web-workout-tracker/workout/src/components/Navbar.js
web-workout-tracker/workout/src/reducers/index.js
web-workout-tracker/workout/src/views/App.js
web-workout-tracker/workout/src/views/DropDownInfo.js
web-workout-tracker/workout/src/views/DropdownLogs.js
web-workout-tracker/workout/src/views/ValidateUser.js
web-workout-tracker/workout/src/views/landing/Workouts.js

When user logs in, if registered, validate user component gets user backend data and sends to redux store. Also has some progress on the edit workouts in PR.

on login, sends backend user data to the redux store

---

web-workout-tracker/workout/src/components/Navbar.js
web-workout-tracker/workout/src/views/BodyGoal.js
web-workout-tracker/workout/src/views/ValidateUser.js
web-workout-tracker/workout/src/views/landing/Landing.js

Refactored code to clean up user_id and body_goal from localStorage. Now we're using Redux store (thisUser object) to grab this info from each component that needs it.

Web cleanup

---

web-workout-tracker/workout/src/components/Marketing.js
web-workout-tracker/workout/src/views/ValidateUser.js
web-workout-tracker/workout/src/views/landing/Landing.js

If user goes to marketing page and hasn't logged out, they will be taken to their dashboard. Works by checking if auth0 cookie is still persisting or not.

if user hasn't logged out, is taken to dashboard instead of marketing

---

web-workout-tracker/node_modules/.yarn-integrity
web-workout-tracker/workout/src/views/DropdownLogs.js
web-workout-tracker/workout/src/views/NoWorkouts.js
web-workout-tracker/workout/src/views/landing/Workouts.js

- Removed thinking emoji. Not consistent with app's iconography.

Removed blob 🤔

---

web-workout-tracker/.gitignore
web-workout-tracker/workout/src/components/Navbar.js

Fixed alignment on the Login button, added additional .gitignore file .

Bug fixing

---

web-workout-tracker/workout/package-lock.json
web-workout-tracker/workout/src/components/SuggestedModal.js
web-workout-tracker/workout/src/components/SuggestedWorkouts.js
web-workout-tracker/workout/src/views/exercise_form/ExerciseForm.js
web-workout-tracker/workout/src/views/exercise_form/ExerciseTypeForm.js

The suggested workouts modal will now send the name of the selected suggested workout and populate the name of the workout in the workout form.
It hasn't... yet.

Suggested workouts now prefills name in workout form
